function [A_sym,B_sym] = AB_symbolicPars(X,u,p)
%AB_SYMBOLICPARS2
%    [A_SYM,B_SYM] = AB_SYMBOLICPARS2(X1,X2,X3,X4,U,B_EQ,B_P,J_EQ,J_P,K_G,M_P,R_M,ETA_G,ETA_M,G,K_M,K_T,L_P,R_MP)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-May-2020 20:30:44

    B_eq = p.B_eq;
    B_p = p.B_p;
    J_eq = p.J_eq;
    J_p = p.J_p;
    K_g = p.K_g;
    M_p = p.M_p;
    R_m = p.R_m;
    eta_g = p.eta_g;
    eta_m = p.eta_m;
    g = p.g;
    k_m = p.k_m;
    k_t = p.k_t;
    l_p = p.l_p;
    r_mp = p.r_mp;
    
    X1 = X(1);
    X2 = X(2);
    X3 = X(3);
    X4 = X(4);

t2 = cos(X3);
t3 = sin(X3);
t4 = K_g.^2;
t5 = M_p.^2;
t6 = X4.^2;
t7 = l_p.^2;
t8 = l_p.^3;
t9 = r_mp.^2;
t10 = J_eq.*J_p;
t11 = J_p.*M_p;
t14 = 1.0./R_m;
t12 = t2.^2;
t13 = t3.^2;
t15 = 1.0./t9;
t16 = J_eq.*M_p.*t7;
t17 = t5.*t7;
t18 = t12.*t17;
t19 = -t18;
t20 = t10+t11+t16+t17+t19;
t21 = 1.0./t20;
t22 = t21.^2;
A_sym = reshape([0.0,0.0,0.0,0.0,1.0,-t14.*t15.*t21.*(B_eq.*J_p.*R_m.*t9+B_eq.*M_p.*R_m.*t7.*t9+J_p.*eta_g.*k_m.*k_t.*t4+M_p.*eta_g.*k_m.*k_t.*t4.*t7),0.0,t14.*t15.*t21.*(B_eq.*M_p.*R_m.*l_p.*t2.*t9+M_p.*eta_g.*k_m.*k_t.*l_p.*t2.*t4),0.0,t14.*t15.*t21.*(R_m.*g.*t9.*t18-R_m.*g.*t9.*t13.*t17+R_m.*l_p.*t2.*t6.*t9.*t11+R_m.*t2.*t5.*t6.*t8.*t9-B_p.*M_p.*R_m.*X4.*l_p.*t3.*t9)-t2.*t3.*t14.*t15.*t17.*t22.*(-B_eq.*J_p.*R_m.*X2.*t9-B_eq.*M_p.*R_m.*X2.*t7.*t9-J_p.*X2.*eta_g.*k_m.*k_t.*t4+R_m.*g.*t2.*t3.*t9.*t17+R_m.*l_p.*t3.*t6.*t9.*t11+R_m.*t3.*t5.*t6.*t8.*t9+J_p.*K_g.*eta_g.*eta_m.*k_t.*r_mp.*u-M_p.*X2.*eta_g.*k_m.*k_t.*t4.*t7+B_p.*M_p.*R_m.*X4.*l_p.*t2.*t9+K_g.*M_p.*eta_g.*eta_m.*k_t.*r_mp.*t7.*u).*2.0,0.0,-t14.*t15.*t21.*(R_m.*t6.*t9.*t18-R_m.*t6.*t9.*t13.*t17+R_m.*g.*l_p.*t2.*t5.*t9+J_eq.*M_p.*R_m.*g.*l_p.*t2.*t9+B_eq.*M_p.*R_m.*X2.*l_p.*t3.*t9+M_p.*X2.*eta_g.*k_m.*k_t.*l_p.*t3.*t4-K_g.*M_p.*eta_g.*eta_m.*k_t.*l_p.*r_mp.*t3.*u)+t2.*t3.*t14.*t15.*t17.*t22.*(B_p.*J_eq.*R_m.*X4.*t9+B_p.*M_p.*R_m.*X4.*t9+R_m.*g.*l_p.*t3.*t5.*t9+R_m.*t2.*t3.*t6.*t9.*t17+J_eq.*M_p.*R_m.*g.*l_p.*t3.*t9-B_eq.*M_p.*R_m.*X2.*l_p.*t2.*t9-M_p.*X2.*eta_g.*k_m.*k_t.*l_p.*t2.*t4+K_g.*M_p.*eta_g.*eta_m.*k_t.*l_p.*r_mp.*t2.*u).*2.0,0.0,t14.*t15.*t21.*(B_p.*M_p.*R_m.*l_p.*t2.*t9+R_m.*X4.*l_p.*t3.*t9.*t11.*2.0+R_m.*X4.*t3.*t5.*t8.*t9.*2.0),1.0,-t14.*t15.*t21.*(B_p.*J_eq.*R_m.*t9+B_p.*M_p.*R_m.*t9+R_m.*X4.*t2.*t3.*t9.*t17.*2.0)],[4,4]);
if nargout > 1
    B_sym = [0.0;t14.*t15.*t21.*(J_p.*K_g.*eta_g.*eta_m.*k_t.*r_mp+K_g.*M_p.*eta_g.*eta_m.*k_t.*r_mp.*t7);0.0;-(K_g.*M_p.*eta_g.*eta_m.*k_t.*l_p.*t2.*t14.*t21)./r_mp];
end
