function dXdt = pendCartC_symbolicPars(X,u,d,p)
%PENDCARTC2
%    V = PENDCARTC2(X1,X2,X3,X4,U,B_EQ,B_P,J_EQ,J_P,K_G,M_P,R_M,ETA_G,ETA_M,G,K_M,K_T,L_P,R_MP)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-May-2020 20:39:30
    
%% Manually edited
    B_eq = p.B_eq;
    B_p = p.B_p;
    J_eq = p.J_eq;
    J_p = p.J_p;
    K_g = p.K_g;
    M_p = p.M_p;
    R_m = p.R_m;
    eta_g = p.eta_g;
    eta_m = p.eta_m;
    g = p.g;
    k_m = p.k_m;
    k_t = p.k_t;
    l_p = p.l_p;
    r_mp = p.r_mp;
    
    X1 = X(1); % x_c
    X2 = X(2); % Dx_c
    X3 = X(3); % alpha
    X4 = X(4); % Dalpha
    
    D_dXc = d(1)/(M_p+J_eq); % disturbance from force
    D_dAlpha = d(2)/(M_p*l_p); % disturbance from torque
%% Autogenerated
t2 = cos(X3);
t3 = sin(X3);
t4 = K_g.^2;
t5 = M_p.^2;
t6 = X4.^2;
t7 = l_p.^2;
t8 = r_mp.^2;
t9 = J_eq.*J_p;
t10 = J_p.*M_p;
t12 = 1.0./R_m;
t11 = t2.^2;
t13 = 1.0./t8;
t14 = J_eq.*M_p.*t7;
t15 = t5.*t7;
t16 = t11.*t15;
t17 = -t16;
t18 = t9+t10+t14+t15+t17;
t19 = 1.0./t18;
dXdt = [X2;
    D_dXc + t12.*t13.*t19.*(-B_eq.*J_p.*R_m.*X2.*t8+R_m.*l_p.^3.*t3.*t5.*t6.*t8-B_eq.*M_p.*R_m.*X2.*t7.*t8-J_p.*X2.*eta_g.*k_m.*k_t.*t4+R_m.*g.*t2.*t3.*t8.*t15+R_m.*l_p.*t3.*t6.*t8.*t10+J_p.*K_g.*eta_g.*eta_m.*k_t.*r_mp.*u-M_p.*X2.*eta_g.*k_m.*k_t.*t4.*t7+B_p.*M_p.*R_m.*X4.*l_p.*t2.*t8+K_g.*M_p.*eta_g.*eta_m.*k_t.*r_mp.*t7.*u);
    X4;
    D_dAlpha + -t12.*t13.*t19.*(B_p.*J_eq.*R_m.*X4.*t8+B_p.*M_p.*R_m.*X4.*t8+R_m.*g.*l_p.*t3.*t5.*t8+R_m.*t2.*t3.*t6.*t8.*t15+J_eq.*M_p.*R_m.*g.*l_p.*t3.*t8-B_eq.*M_p.*R_m.*X2.*l_p.*t2.*t8-M_p.*X2.*eta_g.*k_m.*k_t.*l_p.*t2.*t4+K_g.*M_p.*eta_g.*eta_m.*k_t.*l_p.*r_mp.*t2.*u)];

